### PR TITLE
Suggest using condition title in message instead of stream name

### PR DESCRIPTION
**Pull request by KevDBG**
It would be interesting to change the alarm message with the title. Indeed, the stream name is already in the alarm description.

### CODE REVIEW

**Comment by cglrkn** [comment]
Hi, We will test the recent changes and merge the request accordingly. Thanks for your contribution!

**Comment by pugnacity** [comment]
+1 for this change

**Comment by tnucera** [comment]
Hello, any update for this change?

**Comment by MeralBusraTekinsen** [comment]
hi,
First of all, thank you for your suggestion. While generating message we prefer to be more generic and give more detailed information by taking into consideration all of our customer’s requirements. This plugin is open source and you can change the message depends on your requirements easily. You just need to generate jar file yourself and deploy it to your Graylog server.

**Comment by tnucera** [comment]
This is not very consistent following the last change on alerts in Graylog 2.5 :
https://www.graylog.org/post/announcing-graylog-v2-5

**Pull request closed without merging**
